<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/lib/pdf.php';

try {
    $pdo = db_connect();
    
    $resource = 'expenses';
    $tableName = str_replace('-', '_', $resource);
    $sql = "SELECT ref, category, amount, date, trip, status FROM {$tableName} ORDER BY id ASC";
    $stmt = $pdo->prepare($sql);
    $stmt->execute();
    $rows = $stmt->fetchAll();
    
    echo "Rows fetched: " . count($rows) . "\n";
    foreach ($rows as $r) {
        echo "  - " . json_encode($r) . "\n";
    }
    
    $headers = ['Ref', 'Category', 'Amount', 'Date', 'Trip', 'Status'];
    $dbCols = ['ref', 'category', 'amount', 'date', 'trip', 'status'];
    
    $pdf = new PdfReport('MALUKU LOGISTICS - ' . ucwords(str_replace('-', ' ', $resource)) . ' Report');
    $pdf->setColumns($headers);
    $pdf->setMeta('Generated By', 'Admin User');
    $pdf->setPeriod('', '');
    $pdf->setOrientation('landscape');
    
    foreach ($rows as $r) {
        $pdf->addRow(array_map(fn($c) => $r[$c] ?? '', $dbCols));
    }
    
    $total = 0;
    foreach ($rows as $r) {
        $total += (int)($r['amount'] ?? 0);
    }
    
    $summary = [];
    $summary[] = ['label' => 'Total Records', 'value' => count($rows)];
    $summary[] = ['label' => 'Total Amount', 'value' => 'TZS ' . number_format($total)];
    $pdf->setSummary($summary);
    $pdf->addTotal('Grand Total', 'Amount', 'TZS ' . number_format($total));
    
    $output = $pdf->build();
    file_put_contents(__DIR__ . '/test_debug.pdf', $output);
    echo "PDF generated: " . strlen($output) . " bytes\n";
} catch (Throwable $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    echo $e->getTraceAsString() . "\n";
}
