<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/lib/pdf.php';

try {
    $pdf = new PdfReport('MALUKU LOGISTICS - Expenses Report');
    $pdf->setColumns(['Ref', 'Category', 'Amount', 'Date', 'Trip', 'Status']);
    $pdf->addRow(['EXP-001', 'Fuel', '85000', '2026-07-15', 'TRP-001', 'completed']);
    $pdf->addRow(['EXP-002', 'Maintenance', '120000', '2026-07-16', 'TRP-002', 'pending']);
    $pdf->setSummary([
        ['label' => 'Total Records', 'value' => '2'],
        ['label' => 'Total Amount', 'value' => 'TZS 205,000'],
    ]);
    $pdf->addTotal('Grand Total', 'Amount', 'TZS 205,000');
    $pdf->setMeta('Generated By', 'Admin User');
    $pdf->setPeriod('2026-07-01', '2026-07-31');
    $pdf->setOrientation('landscape');
    
    $output = $pdf->build();
    file_put_contents(__DIR__ . '/test_standalone.pdf', $output);
    echo "SUCCESS: PDF generated, size=" . strlen($output) . "\n";
} catch (Throwable $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    echo "FILE: " . $e->getFile() . " LINE: " . $e->getLine() . "\n";
    echo $e->getTraceAsString() . "\n";
}
