<?php
require_once __DIR__ . '/config.php';
require_once __DIR__ . '/lib/pdf.php';

try {
    $pdf = new PdfReport('MALUKU LOGISTICS - Expenses Report');
    $pdf->setColumns(['Ref', 'Category', 'Amount', 'Date', 'Trip', 'Status']);
    
    $categories = ['Fuel', 'Maintenance', 'Insurance', 'Tolls', 'Parking', 'Repairs', 'Tyres', 'Service'];
    $statuses = ['completed', 'pending', 'in_progress', 'cancelled'];
    
    for ($i = 1; $i <= 50; $i++) {
        $cat = $categories[array_rand($categories)];
        $status = $statuses[array_rand($statuses)];
        $amount = rand(50000, 500000);
        $pdf->addRow([
            'EXP-' . str_pad($i, 3, '0', STR_PAD_LEFT),
            $cat,
            (string)$amount,
            '2026-07-' . str_pad(rand(1, 28), 2, '0', STR_PAD_LEFT),
            'TRP-' . str_pad(rand(1, 20), 3, '0', STR_PAD_LEFT),
            $status
        ]);
    }
    
    $pdf->setSummary([
        ['label' => 'Total Records', 'value' => '50'],
        ['label' => 'Total Amount', 'value' => 'TZS 12,500,000'],
    ]);
    $pdf->addTotal('Grand Total', 'Amount', 'TZS 12,500,000');
    $pdf->setMeta('Generated By', 'Admin User');
    $pdf->setPeriod('2026-07-01', '2026-07-31');
    $pdf->setOrientation('landscape');
    
    $output = $pdf->build();
    file_put_contents(__DIR__ . '/test_large.pdf', $output);
    echo "SUCCESS: PDF generated, size=" . strlen($output) . "\n";
} catch (Throwable $e) {
    echo "ERROR: " . $e->getMessage() . "\n";
    echo "FILE: " . $e->getFile() . " LINE: " . $e->getLine() . "\n";
}
