<?php
/**
 * Professional PDF report generator.
 */

class PdfReport
{
    private string $title;
    private array $columns = [];
    private array $rows = [];
    private array $totals = [];
    private array $summary = [];
    private array $meta = [];
    private ?string $periodFrom = null;
    private ?string $periodTo = null;
    private string $orientation = 'landscape';
    private array $colWeights = [];

    private const PAGE_W_PORTRAIT = 595;
    private const PAGE_H_PORTRAIT = 842;
    private const PAGE_W_LANDSCAPE = 842;
    private const PAGE_H_LANDSCAPE = 595;
    private const MARGIN = 30;
    private const HEADER_BRAND_H = 44;
    private const HEADER_INFO_H = 38;
    private const SUMMARY_CARD_H = 44;
    private const SUMMARY_CARD_GAP = 8;
    private const TABLE_HEADER_H = 28;
    private const ROW_PADDING = 7;
    private const ROW_LINE_H = 12;
    private const FONT_SIZE = 8;
    private const FOOTER_H = 22;
    private const CHAR_W = 0.52;

    private float $usableW = 0;
    private float $bodyStartY = 0;
    private array $colWidths = [];
    private array $colAligns = [];

    public function __construct(string $title)
    {
        $this->title = $title;
        $this->setMeta('Generated By', 'Admin User');
    }

    public function setColumns(array $cols): void
    {
        $this->columns = $cols;
        $this->colWeights = $this->defaultWeights($cols);
        $this->colAligns = $this->inferAligns($cols);
    }

    public function setColumnWeights(array $weights): void
    {
        if (count($weights) === count($this->columns)) {
            $this->colWeights = $weights;
        }
    }

    private function defaultWeights(array $cols): array
    {
        $w = [];
        foreach ($cols as $c) {
            $cl = strtolower($c);
            if (in_array($cl, ['amount', 'price', 'qty', 'min', 'year', 'trips', 'total trips', 'total_trips', 'value', 'weight', 'due'], true)) {
                $w[] = 1.6;
            } elseif (in_array($cl, ['ref', 'date', 'status', 'plate', 'license', 'phone', 'email', 'method'], true)) {
                $w[] = 1.2;
            } elseif (in_array($c, ['Category', 'Origin', 'Destination', 'Vehicle', 'Driver', 'Horse', 'Trailer'], true)) {
                $w[] = 1.7;
            } elseif (in_array($cl, ['name', 'client', 'customer', 'supplier', 'description', 'category'], true)) {
                $w[] = 2.0;
            } else {
                $w[] = 1.4;
            }
        }
        return $w;
    }

    private function inferAligns(array $cols): array
    {
        $a = [];
        foreach ($cols as $c) {
            $cl = strtolower($c);
            if (in_array($cl, ['amount', 'price', 'total', 'value', 'due', 'balance', 'qty', 'min', 'year', 'trips', 'weight'], true)) {
                $a[] = 'right';
            } elseif (in_array($cl, ['date', 'status'], true)) {
                $a[] = 'center';
            } else {
                $a[] = 'left';
            }
        }
        return $a;
    }

    public function addRow(array $row): void { $this->rows[] = $row; }
    public function setRows(array $rows): void { $this->rows = $rows; }

    public function addTotal(string $label, ?string $amountColKey, ?string $amountValue): void
    {
        $this->totals[] = ['label' => $label, 'amountColKey' => $amountColKey, 'amountValue' => $amountValue];
    }

    public function setSummary(array $summary): void { $this->summary = $summary; }

    public function setMeta(string $key, string $value): void { $this->meta[$key] = $value; }

    public function setPeriod(?string $from, ?string $to): void
    {
        $this->periodFrom = $from;
        $this->periodTo = $to;
    }

    public function setOrientation(string $orientation): void
    {
        $this->orientation = $orientation === 'portrait' ? 'portrait' : 'landscape';
    }

    private function escape(string $s): string
    {
        $s = preg_replace('/[^\x20-\x7E\xA0-\xFF]/', '', $s);
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $s);
    }

    private function textOp(string $text, float $x, float $y, string $font = 'F2', float $size = 8, string $fillRgb = '0 0 0'): string
    {
        $rx = round($x, 1);
        $ry = round($y, 1);
        return "BT /{$font} {$size} Tf {$fillRgb} rg 1 0 0 1 {$rx} {$ry} Tm ({$this->escape($text)}) Tj ET";
    }

    private function grayRect(float $x, float $y, float $w, float $h, float $gray): string
    {
        return "q {$x} {$y} {$w} {$h} re {$gray} g f Q";
    }

    private function colorRect(float $x, float $y, float $w, float $h, float $r, float $g, float $b): string
    {
        return "q {$x} {$y} {$w} {$h} re {$r} {$g} {$b} rg f Q";
    }

    private function rgbFromHex(string $hex): array
    {
        $h = ltrim($hex, '#');
        return [
            hexdec(substr($h, 0, 2)) / 255,
            hexdec(substr($h, 2, 2)) / 255,
            hexdec(substr($h, 4, 2)) / 255,
        ];
    }

    private function lineOp(float $x1, float $y1, float $x2, float $y2, float $gray = 0.5): string
    {
        return "q {$x1} {$y1} m {$x2} {$y2} l {$gray} G S Q";
    }

    private function mb_len(string $s): int
    {
        return function_exists('mb_strlen') ? mb_strlen($s) : strlen($s);
    }

    private function mb_sub(string $s, int $start, int $len = 2147483647): string
    {
        if (function_exists('mb_substr')) {
            return mb_substr($s, $start, $len);
        }
        return substr($s, $start, $len);
    }

    private function textWidth(string $text, float $fontSize = 8): float
    {
        return $this->mb_len($text) * $fontSize * self::CHAR_W;
    }

    private function wrapText(string $text, float $maxWidth, float $fontSize = 8): array
    {
        if ($text === '') return [''];
        $charW = $fontSize * self::CHAR_W;
        $maxChars = (int)ceil($maxWidth / $charW);
        if ($maxChars < 1) $maxChars = 1;

        if ($this->mb_len($text) <= $maxChars) return [$text];

        $words = preg_split('/\s+/', $text, -1, PREG_SPLIT_NO_EMPTY);
        if (count($words) <= 1) {
            return $this->splitLongWord($text, $maxChars);
        }

        $lines = [];
        $current = '';
        foreach ($words as $word) {
            $test = $current === '' ? $word : $current . ' ' . $word;
            if ($this->mb_len($test) <= $maxChars) {
                $current = $test;
            } else {
                if ($current !== '') $lines[] = $current;
                if ($this->mb_len($word) > $maxChars) {
                    $current = '';
                    $lines = array_merge($lines, $this->splitLongWord($word, $maxChars));
                } else {
                    $current = $word;
                }
            }
        }
        if ($current !== '') $lines[] = $current;
        return $lines;
    }

    private function splitLongWord(string $word, int $maxChars): array
    {
        $lines = [];
        while ($this->mb_len($word) > 0) {
            $lines[] = $this->mb_sub($word, 0, $maxChars);
            $word = $this->mb_sub($word, $maxChars);
        }
        return $lines;
    }

    private function calculateLayout(): array
    {
        $isLandscape = $this->orientation === 'landscape';
        $pageW = $isLandscape ? self::PAGE_W_LANDSCAPE : self::PAGE_W_PORTRAIT;
        $pageH = $isLandscape ? self::PAGE_H_LANDSCAPE : self::PAGE_H_PORTRAIT;
        $margin = self::MARGIN;
        $usableW = $pageW - 2 * $margin;
        $bodyStartY = $pageH - $margin - self::HEADER_BRAND_H - self::HEADER_INFO_H - 10;

        $n = count($this->columns);
        $colWidths = [];
        $colAligns = [];
        if ($n > 0) {
            $weights = $this->colWeights;
            $totalWeight = array_sum($weights);
            if ($totalWeight <= 0) $totalWeight = count($weights);
            $colWidths = array_map(function($w) use ($usableW, $totalWeight) {
                $width = ($w / $totalWeight) * $usableW;
                return max(36, $width);
            }, $weights);
            $colAligns = $this->colAligns;
        }

        return [
            'pageW' => $pageW,
            'pageH' => $pageH,
            'usableW' => $usableW,
            'bodyStartY' => $bodyStartY,
            'colWidths' => $colWidths,
            'colAligns' => $colAligns,
        ];
    }

    private function calculateRowHeight(array $row, array $layout): float
    {
        $maxLines = 1;
        foreach ($this->columns as $i => $col) {
            $cell = $row[$i] ?? '';
            $display = is_array($cell) ? ($cell['value'] ?? '') : (string)$cell;
            $cw = $layout['colWidths'][$i];
            $wrapped = $this->wrapText($display, $cw - 12, self::FONT_SIZE);
            $maxLines = max($maxLines, count($wrapped));
        }
        return max(22, $maxLines * self::ROW_LINE_H + 2 * self::ROW_PADDING);
    }

    private function paginate(array $layout): array
    {
        $usableH = $layout['bodyStartY'] - self::MARGIN - self::FOOTER_H - 20;
        $summaryH = !empty($this->summary) ? self::SUMMARY_CARD_H + self::SUMMARY_CARD_GAP : 0;
        $allPages = [];
        $currentPageRows = [];
        $currentPageHeight = 0;

        foreach ($this->rows as $row) {
            $rowH = $this->calculateRowHeight($row, $layout);
            $minSpaceNeeded = $rowH + 30;

            $available = $usableH - $currentPageHeight - (empty($allPages) ? $summaryH : 0);
            if ($currentPageRows !== [] && $available < $minSpaceNeeded) {
                $allPages[] = $currentPageRows;
                $currentPageRows = [];
                $currentPageHeight = 0;
            }

            $currentPageRows[] = $row;
            $currentPageHeight += $rowH;
        }

        if ($currentPageRows) $allPages[] = $currentPageRows;
        if (empty($allPages)) $allPages[] = [];

        return $allPages;
    }

    private function drawHeader(float $pageNum, int $totalPages, string $dateRange, array $layout): array
    {
        $lines = [];
        $x = self::MARGIN;
        $pageW = $layout['pageW'];
        $pageH = $layout['pageH'];
        $y = $pageH - self::MARGIN;

        $primary = $this->rgbFromHex('#003333');
        $accent = $this->rgbFromHex('#99CC33');

        $brandY = $y - self::HEADER_BRAND_H;

        $lines[] = $this->colorRect($x, $brandY, $layout['usableW'], self::HEADER_BRAND_H, $primary[0], $primary[1], $primary[2]);
        $lines[] = $this->colorRect($x + $layout['usableW'] - 6, $brandY, 6, self::HEADER_BRAND_H, $accent[0], $accent[1], $accent[2]);

        $lines[] = $this->textOp('MALUKU LOGISTICS', $x + 12, $y - 18, 'F1', 14, '1 1 1');
        $lines[] = $this->textOp('Transit & General Supply Management System', $x + 12, $y - 30, 'F2', 8, '1 1 1');
        $lines[] = $this->textOp('Msimbazi Street, Dar es Salaam, Tanzania', $x + 12, $y - 38, 'F2', 7, '1 1 1');

        $lineY = $brandY - 12;
        $lines[] = $this->textOp($this->title, $x, $lineY, 'F1', 12);

        $metaRightStart = $pageW - self::MARGIN;
        $lineY -= 14;
        $lines[] = $this->textOp('Period: ' . ($dateRange ?: 'All'), $x, $lineY, 'F2', 8);
        $lines[] = $this->textOp('Generated: ' . date('Y-m-d H:i'), $x + 140, $lineY, 'F2', 8);

        $lineY -= 12;
        $generatedBy = $this->meta['Generated By'] ?? 'Admin User';
        $lines[] = $this->textOp('Generated By: ' . $generatedBy, $x, $lineY, 'F2', 8);
        $lines[] = $this->textOp('Page ' . $pageNum . ' of ' . $totalPages, $x + 140, $lineY, 'F2', 8);

        $sepY = $lineY - 10;
        $lines[] = $this->lineOp($x, $sepY, $x + $layout['usableW'], $sepY, 0.85);

        return $lines;
    }

    private function drawSummaryCards(float $y, array $layout): array
    {
        $lines = [];
        if (empty($this->summary)) return $lines;

        $x = self::MARGIN;
        $boxW = $layout['usableW'];
        $items = array_values($this->summary);
        $cols = 3;
        $colW = ($boxW - self::SUMMARY_CARD_GAP * ($cols - 1)) / $cols;
        $cardH = self::SUMMARY_CARD_H;

        $startY = $y - self::SUMMARY_CARD_H - 4;
        $rows = (int)ceil(count($items) / $cols);
        $totalH = self::SUMMARY_CARD_H + 20 + ($rows - 1) * (self::SUMMARY_CARD_H + self::SUMMARY_CARD_GAP);
        $lines[] = $this->grayRect($x, $startY - 2, $boxW, $totalH, 0.96);
        $lines[] = $this->textOp('REPORT SUMMARY', $x + 8, $y - 10, 'F1', 9);

        foreach ($items as $idx => $item) {
            $col = $idx % $cols;
            $row = (int)floor($idx / $cols);
            $cx = $x + $col * ($colW + self::SUMMARY_CARD_GAP);
            $cy = $startY - $row * (self::SUMMARY_CARD_H + self::SUMMARY_CARD_GAP);

            $innerX = $cx + 8;
            $innerW = $colW - 16;
            $innerTopY = $cy;
            $innerBottomY = $cy - self::SUMMARY_CARD_H + 4;

            $lines[] = $this->grayRect($innerX, $innerBottomY, $innerW, self::SUMMARY_CARD_H - 4, 0.94);

            $label = is_array($item) ? ($item['label'] ?? '') : (string)$item;
            $value = is_array($item) ? ($item['value'] ?? '') : '';

            $labelY = $innerTopY - 12;
            $valueY = $innerTopY - 28;
            $lines[] = $this->textOp($label, $innerX + 6, $labelY, 'F1', 8);
            if ($value !== '') {
                $lines[] = $this->textOp($value, $innerX + 6, $valueY, 'F2', 9);
            }
        }

        return $lines;
    }

    private function drawTableHeader(float $y, array $layout): array
    {
        $lines = [];
        $x = self::MARGIN;
        $primary = $this->rgbFromHex('#003333');
        $accent = $this->rgbFromHex('#99CC33');
        $topY = $y;
        $bottomY = $y - self::TABLE_HEADER_H;

        $lines[] = $this->colorRect($x, $bottomY, $layout['usableW'], self::TABLE_HEADER_H, $primary[0], $primary[1], $primary[2]);
        $lines[] = $this->colorRect($x, $bottomY, $layout['usableW'], 2, $accent[0], $accent[1], $accent[2]);

        $cellX = $x;
        $textY = $y - 17;
        foreach ($this->columns as $i => $col) {
            $cw = $layout['colWidths'][$i];
            $display = $this->escape($col);
            $availW = $cw - 10;
            $maxChars = (int)ceil($availW / (self::FONT_SIZE * self::CHAR_W));
            $display = $this->mb_len($display) > $maxChars ? $this->mb_sub($display, 0, $maxChars - 2) . '..' : $display;

            $align = $layout['colAligns'][$i];
            if ($align === 'center') {
                $estW = $this->textWidth($display, self::FONT_SIZE);
                $tx = $cellX + ($cw - $estW) / 2;
            } elseif ($align === 'right') {
                $estW = $this->textWidth($display, self::FONT_SIZE);
                $tx = $cellX + $cw - $estW - 6;
            } else {
                $tx = $cellX + 6;
            }
            $lines[] = $this->textOp($display, $tx, $textY, 'F1', self::FONT_SIZE, '1 1 1');
            $cellX += $cw;
        }

        return $lines;
    }

    private function drawRow(float $x, float $y, array $row, bool $isAlt, float $rowHeight, array $layout): array
    {
        $lines = [];
        $cellX = $x;
        $topY = $y;
        $bottomY = $y - $rowHeight;

        if ($isAlt) {
            $lines[] = $this->grayRect($x, $bottomY + 1, $layout['usableW'], $rowHeight - 1, 0.96);
        }

        $lines[] = $this->lineOp($x, $topY, $x + $layout['usableW'], $topY, 0.45);
        $lines[] = $this->lineOp($x, $bottomY, $x + $layout['usableW'], $bottomY, 0.45);
        foreach ($layout['colWidths'] as $cw) {
            $lines[] = $this->lineOp($cellX, $topY, $cellX, $bottomY, 0.35);
            $cellX += $cw;
        }

        $cellX = $x;
        $baseTextY = $y - self::ROW_PADDING;
        foreach ($this->columns as $i => $col) {
            $cell = $row[$i] ?? '';
            $display = is_array($cell) ? ($cell['value'] ?? '') : (string)$cell;
            $cw = $layout['colWidths'][$i];
            $align = $layout['colAligns'][$i];

            $isCurrency = false;
            $cl = strtolower($col);
            if (in_array($cl, ['amount', 'price', 'total', 'value', 'due', 'balance'], true)) {
                $isCurrency = true;
            }

            if ($isCurrency && is_numeric(str_replace(['TZS ', ','], '', $display))) {
                $display = 'TZS ' . number_format((int)round(floatval(str_replace(['TZS ', ','], '', $display))));
            }

            $wrapped = $this->wrapText($display, $cw - 12, self::FONT_SIZE);
            $lineCount = count($wrapped);

            if ($col === 'Status' && !empty(trim($display))) {
                $badge = $this->drawStatusBadge($cellX, $y, $rowHeight, $cw, $display);
                $lines = array_merge($lines, $badge);
                $lineCount = 0;
            }

            for ($l = 0; $l < $lineCount; $l++) {
                $lineText = $this->escape($wrapped[$l]);
                $cellTextY = $baseTextY - ($l * self::ROW_LINE_H);

                if ($align === 'center') {
                    $estW = $this->textWidth($lineText, self::FONT_SIZE);
                    $tx = $cellX + ($cw - $estW) / 2;
                    $lines[] = $this->textOp($lineText, $tx, $cellTextY, 'F2', self::FONT_SIZE);
                } elseif ($align === 'right') {
                    $estW = $this->textWidth($lineText, self::FONT_SIZE);
                    $tx = $cellX + $cw - $estW - 8;
                    if ($tx < $cellX + 2) $tx = $cellX + 2;
                    $lines[] = $this->textOp($lineText, $tx, $cellTextY, 'F2', self::FONT_SIZE);
                } else {
                    $lines[] = $this->textOp($lineText, $cellX + 8, $cellTextY, 'F2', self::FONT_SIZE);
                }
            }

            $cellX += $cw;
        }

        return $lines;
    }

    private function drawStatusBadge(float $cellX, float $topY, float $rowHeight, float $cellWidth, string $status): array
    {
        $s = strtolower($status);
        $colors = [
            'completed' => ['#dcfce7', '#166534'],
            'paid' => ['#dcfce7', '#166534'],
            'approved' => ['#dcfce7', '#166534'],
            'active' => ['#dcfce7', '#166534'],
            'delivered' => ['#dcfce7', '#166534'],
            'pending' => ['#fef3c7', '#92400e'],
            'in_transit' => ['#fef3c7', '#92400e'],
            'cancelled' => ['#fee2e2', '#991b1b'],
            'inactive' => ['#fee2e2', '#991b1b'],
            'overdue' => ['#fee2e2', '#991b1b'],
            'maintenance' => ['#dbeafe', '#1e40af'],
            'on_leave' => ['#dbeafe', '#1e40af'],
            'low_stock' => ['#dbeafe', '#1e40af'],
        ];

        $bgHex = '#f3f4f6';
        $textColorHex = '#374151';
        if (isset($colors[$s])) {
            $bgHex = $colors[$s][0];
            $textColorHex = $colors[$s][1];
        }

        $bgRgb = $this->rgbFromHex($bgHex);
        $textRgb = $this->rgbFromHex($textColorHex);
        $textWidth = $this->textWidth($status, self::FONT_SIZE);
        $badgeW = $textWidth + 16;
        $badgeH = 18;

        $badgeX = $cellX + ($cellWidth - $badgeW) / 2;
        $badgeY = $topY - $rowHeight / 2 - $badgeH / 2;

        $ops = [];
        $ops[] = $this->colorRect($badgeX, $badgeY, $badgeW, $badgeH, $bgRgb[0], $bgRgb[1], $bgRgb[2]);
        $textColorRgb = $textRgb[0] . ' ' . $textRgb[1] . ' ' . $textRgb[2];
        $ops[] = $this->textOp($status, $badgeX + 8, $badgeY + 11, 'F2', self::FONT_SIZE, $textColorRgb);

        return $ops;
    }

    private function drawTotalRow(float $x, float $y, array $total, array $layout): array
    {
        $lines = [];
        $label = $total['label'] ?? '';
        $amount = $total['amountValue'] ?? '';
        $colIdx = $total['amountColKey'] !== null ? array_search($total['amountColKey'], $this->columns, true) : count($this->columns) - 1;
        if ($colIdx === false) $colIdx = count($this->columns) - 1;

        $topY = $y;
        $bottomY = $y - self::TABLE_HEADER_H;

        $lines[] = $this->grayRect($x, $bottomY, $layout['usableW'], self::TABLE_HEADER_H, 0.88);
        $accent = $this->rgbFromHex('#99CC33');
        $lines[] = $this->colorRect($x, $topY - 1, $layout['usableW'], 2, $accent[0], $accent[1], $accent[2]);

        $lines[] = $this->textOp($label, $x + 8, $y - 15, 'F1', 9);

        $cx = $x;
        for ($i = 0; $i <= $colIdx && $i < count($this->columns); $i++) {
            $cx += $layout['colWidths'][$i];
        }
        $cx -= ($layout['colWidths'][$colIdx] ?? 100);

        $amountStr = (string)$amount;
        $estW = $this->textWidth($amountStr, 9);
        $tx = $cx + ($layout['colWidths'][$colIdx] ?? 100) - $estW - 8;
        if ($tx < $cx + 2) $tx = $cx + 2;
        $lines[] = $this->textOp($amountStr, $tx, $y - 15, 'F1', 9);

        return $lines;
    }

    private function drawFooter(float $pageNum, int $totalPages, array $layout): array
    {
        $lines = [];
        $y = self::MARGIN - 8;
        $x = self::MARGIN;
        $lines[] = $this->lineOp($x, $y + 14, $x + $layout['usableW'], $y + 14, 0.85);
        $lines[] = $this->textOp('MALUKU LOGISTICS - Confidential', $x, $y, 'F2', 7);
        $lines[] = $this->textOp('Page ' . $pageNum . ' of ' . $totalPages, $x + $layout['usableW'] - 50, $y, 'F2', 7);
        return $lines;
    }

    public function build(): string
    {
        $layout = $this->calculateLayout();
        $allPages = $this->paginate($layout);
        $totalPages = count($allPages);

        $objects = [];
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';

        $fonts = [
            3 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',
            4 => '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
        ];

        $objNum = 5;
        $pageKids = [];

        $from = clean_string($_GET['from'] ?? '');
        $to = clean_string($_GET['to'] ?? '');
        $dateRange = '';
        if ($from || $to) {
            $dateRange = ($from ? $from : '...') . ' to ' . ($to ? $to : '...');
        } else {
            $dateRange = 'All dates';
        }

        foreach ($allPages as $p => $pageRows) {
            $pageNum = $p + 1;
            $content = [];

            $content = array_merge($content, $this->drawHeader($pageNum, $totalPages, $dateRange, $layout));
            $bodyY = $layout['bodyStartY'];

            if ($p === 0 && !empty($this->summary)) {
                $summaryLines = $this->drawSummaryCards($bodyY, $layout);
                $content = array_merge($content, $summaryLines);
                $bodyY -= self::SUMMARY_CARD_H + self::SUMMARY_CARD_GAP;
            }

            $content = array_merge($content, $this->drawTableHeader($bodyY, $layout));
            $bodyY -= self::TABLE_HEADER_H;

            foreach ($pageRows as $idx => $row) {
                $isAlt = ($idx % 2 === 1);
                $rowH = $this->calculateRowHeight($row, $layout);
                $content = array_merge($content, $this->drawRow(self::MARGIN, $bodyY, $row, $isAlt, $rowH, $layout));
                $bodyY -= $rowH;
            }

            foreach ($this->totals as $total) {
                $content = array_merge($content, $this->drawTotalRow(self::MARGIN, $bodyY, $total, $layout));
                $bodyY -= self::TABLE_HEADER_H;
            }

            $content = array_merge($content, $this->drawFooter($pageNum, $totalPages, $layout));

            $contentStr = implode("\n", $content);
            $contentObj = $objNum + 1;

            $objects[$contentObj] = '<< /Length ' . strlen($contentStr) . ' >>\nstream\n' . $contentStr . '\nendstream';
            $objects[$objNum] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ' . $layout['pageW'] . ' ' . $layout['pageH'] . '] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ' . $contentObj . ' 0 R >>';

            $pageKids[] = $objNum . ' 0 R';
            $objNum += 2;
        }

        $objects[2] = '<< /Type /Pages /Kids [' . implode(' ', $pageKids) . '] /Count ' . $totalPages . ' >>';

        foreach ($fonts as $k => $v) {
            $objects[$k] = $v;
        }

        $pdf = "%PDF-1.4\n";
        $offsets = [];
        ksort($objects);
        foreach ($objects as $num => $body) {
            $offsets[$num] = strlen($pdf);
            $pdf .= $num . " 0 obj\n" . $body . "\nendobj\n";
        }

        $xrefPos = strlen($pdf);
        $pdf .= "xref\n";
        $pdf .= "0 " . (count($objects) + 1) . "\n";
        $pdf .= "0000000000 65535 f \n";
        ksort($offsets);
        foreach ($offsets as $off) {
            $pdf .= str_pad($off, 10, '0', STR_PAD_LEFT) . " 00000 n \n";
        }
        $pdf .= "trailer\n<< /Size " . (count($objects) + 1) . " /Root 1 0 R >>\n";
        $pdf .= "startxref\n" . $xrefPos . "\n%%EOF";

        return $pdf;
    }

    public function output(string $filename = 'report.pdf'): void
    {
        $pdf = $this->build();
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($pdf));
        header('Cache-Control: no-store, no-cache, must-revalidate');
        echo $pdf;
        exit;
    }

    public function toString(): string
    {
        return $this->build();
    }
}
